### ISSUE TITLE
I think there is a problem with content-length handling for some servers:

### ISSUE THREAD

**Issue by cryptomail** [nghialv/Net#17]
In NetRequestSerialization.swift
as a test, I took out the content length, and my php service only THEN parsed the content properly from a POST.
Here is the snippit with the line commented out.
I can look into this further if you want and make a patch if you want.

The specification for post bodies is that if there is no formal content length specified, then the behavior is to read until EOF.

PHP specifically did not parse the payload properly if content length was specified.

if paramsData != nil {
                    request.setValue(contentType, forHTTPHeaderField: "Content-Type")
                    //request.setValue("\(paramsData?.length)", forHTTPHeaderField: "Content-Length")
                    request.HTTPBody = paramsData
                }

**Comment by chrisharrison** [comment]
I logged the request data that I was recieving from my nginx server, I was getting the error: "Client sent invalid Content-Length header while reading client request headers". The content length was set as Optional(42) which is Swift outputting an optional String type. Obviously it should just be Optional(42).

The fix is to go to NetRequestSerialization.swift and fix the line:
request.setValue("(paramsData?.length)", forHTTPHeaderField: "Content-Length")

to:
if(paramsData != nil) {
request.setValue("(paramsData!.length)", forHTTPHeaderField: "Content-Length")
}

**Comment by cryptomail** [comment]
Awesome find. Probably should make a pr

On Sunday, January 25, 2015, Chris Harrison <notifications@github.com>
wrote:

> I logged the request data that I was recieving from my nginx server, I was
> getting the error: "Client sent invalid Content-Length header while reading
> client request headers". The content length was set as Optional(42) which
> is Swift outputting an optional String type. Obviously it should just be
> Optional(42).
>
> The fix is to go to NetRequestSerialization.swift and fix the line:
> request.setValue("(paramsData?.length)", forHTTPHeaderField:
> "Content-Length")
>
> to:
> if(paramsData != nil) {
> request.setValue("(paramsData!.length)", forHTTPHeaderField:
> "Content-Length")
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nghialv/Net/issues/17#issuecomment-71414670>.
>


-- 
http://www.cryptomail.org NOW 100% defunct!

**Comment by nghialv** [comment]
Thank @cryptomail and @chrisharrison . I have just fixed this problem. Please pull the new code.

**Comment by chrisharrison** [comment]
Thanks @nghialv for the library. One thing you might also consider is making Net.httpRequest() public. If you have an API with different verbs you may want to specify the verb but have the same output handling without writing four different methods for GET, POST, PUT, DELETE that all do the same thing. That's why I've modified my copy to make httpRequest public - but I think you should have this as the default in the library. Just my suggestion.
