### ISSUE TITLE
post error

### ISSUE THREAD

**Issue by kuanglijun312** [nghialv/Net#18]
Optional(Error Domain=HTTP_ERROR_CODE Code=400 "The operation couldn’t be completed. (HTTP_ERROR_CODE error 400.)")

some post error;

**Comment by chrisharrison** [comment]
I am also getting Error 400 returned from my server on all POST requests. So far, I've tested GET and PUT and they work.

**Comment by chrisharrison** [comment]
I logged the request data that I was recieving from my nginx server, I was getting the error: "Client sent invalid Content-Length header while reading client request headers". The content length was set as Optional(42) which is Swift outputting an optional String type. Obviously it should just be Optional(42).

The fix is to go to NetRequestSerialization.swift and fix the line:
request.setValue("\(paramsData?.length)", forHTTPHeaderField: "Content-Length")

to:
if(paramsData != nil) {
    request.setValue("\(paramsData!.length)", forHTTPHeaderField: "Content-Length")
}

**Comment by kuanglijun312** [comment]
Work!Thank you!!
